flag_management:
  # this section will govern all default rules of Flags
  default_rules:
    carryforward: boolean?
    ignore: [path]?
    paths: [path]?
    statuses: [ #note, statuses are an array
      name_prefix: string (r"^[\w\-\.]+$")
      type: OR("project", "patch", "changes")
      target: OR("auto", percent)?
      include_changes: OR("auto", precent)?
      threshold: percent?
      **normal status attributes
    ]?

flags:
  cpu:
    paths:
      - solo/args
      - solo/losses
      - solo/methods
      - solo/utils
      - !solo/methods/dali.py
      - !solo/utils/dali_dataloader.py
    carryforward: true
  dali:
    paths:
      - solo/methods/dali.py
      - solo/utils/dali_dataloader.py
    carryforward: true

comment: 
  show_carryforward_flags: false
