flags:
  cpu:
    paths:
      - solo/args
      - solo/losses
      - solo/methods
      - solo/utils
      - !solo/methods/dali.py
      - !solo/utils/dali_dataloader.py
    carryforward: true
  dali:
    paths:
      - solo/methods/dali.py
      - solo/utils/dali_dataloader.py
    carryforward: true

comment: 
  show_carryforward_flags: true
