version: 2

build:
  image: latest

# This part is necessary otherwise the project is not built
# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .

# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
  include: all